---
# flog json
apiVersion: v1
kind: Pod
metadata:
  name: flog-json
spec:
  containers:
    - name: flog-json
      image: nginx:1.20
      resources:
        limits:
          cpu: 25m
          memory: 128Mi
      env:
        - name: FLOG_VERSION
          value: 0.6.0-20220826
        - name: GITHUB_HOST
          value: github.com
      args:
        - /bin/bash
        - -xec
        - |
          curl -fsSL https://kervin-solutions.s3.cn-north-1.amazonaws.com.cn/get-flog.sh | bash
          mkdir -p /var/log/json
          /usr/bin/flog -d 1s -l -f json | tee /var/log/json/access.log

---
# flog apache
apiVersion: v1
kind: Pod
metadata:
  name: flog-apache
spec:
  containers:
    - name: flog-apache
      image: nginx:1.20
      resources:
        limits:
          cpu: 25m
          memory: 128Mi
      env:
        - name: FLOG_VERSION
          value: 0.6.0-20220826
        - name: GITHUB_HOST
          value: github.com
      args:
        - /bin/bash
        - -xec
        - |
          curl -fsSL https://kervin-solutions.s3.cn-north-1.amazonaws.com.cn/get-flog.sh | bash
          mkdir -p /var/log/apache/
          /usr/bin/flog -d 2s -f apache_common -l | tee /var/log/apache/access.log